name: Pyzotero

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Build and Test Wheels
        uses: pypa/cibuildwheel@v2.3.0
        env:
          CIBW_BEFORE_BUILD: pip install numpy cython
          CIBW_TEST_REQUIRES: setuptools pytest numpy cython
          CIBW_TEST_COMMAND: 'pytest {package}'
          CIBW_BUILD: cp3{6,7,8,9,10}-manylinux_x86_64

      - name: Upload tested wheels as artifact
        uses: actions/upload-artifact@v2
        with:
          name: wheels-${{ matrix.os }}
          path: |
            ./wheelhouse/*.whl

  coveralls_finish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel-finished: true

  release_artifacts:
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    name: Release repaired and tested wheels
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Download compressed artifacts
      id: download
      uses: actions/download-artifact@v2
      with:
        path: ./artifacts

    - name: 'List downloaded files'
      run: ls ${{ steps.download.outputs.download-path }}/**/*.*

    - name: Create release and upload wheels
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: "${{ steps.download.outputs.download-path }}/**/*.whl"
        token: ${{ secrets.GITHUB_TOKEN }}
